# Use postgres/geheim user/password credentials
version: '3.9'

services:

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: geheim

  adminer:
    image: adminer
    ports:
      - 8080:8080
