curl -X PUT "localhost:9200/product" -H 'Content-Type: application/json' -d'
{
   "settings":{
      "index":{
         "number_of_shards":1,
         "number_of_replicas":1
      },
      "analysis":{
         "filter":{
            "german_decompounder":{
               "type":"hyphenation_decompounder",
               "word_list_path":"analysis/dictionary-de.txt",
               "hyphenation_patterns_path":"analysis/de_DR.xml",
               "only_longest_match":true,
               "min_subword_size":3
            },
            "german_dict_decompounder":{
               "type":"dictionary_decompounder",
               "word_list_path":"analysis/dictionary-de.txt",
               "hyphenation_patterns_path":"analysis/de_DR.xml",
               "only_longest_match":true,
               "min_subword_size":3
            },
            "german_stemmer":{
               "type":"stemmer",
               "language":"light_german"
            },
            "german_stop": {
               "type":       "stop",
               "stopwords":  "_german_"
            }
         },
         "analyzer":{
            "german":{
               "type":"standard",
               "stopwords": "_none_"
            },
            "german_stemmer":{
               "type":"custom",
               "tokenizer":"standard",
               "filter":[
                  "lowercase",
                  "german_stemmer"
               ]
            },
            "german_normalization":{
               "type":"custom",
               "tokenizer":"standard",
               "filter":[
                  "lowercase",
                  "german_normalization"
               ]
            },
            "german_dict_decompound":{
               "type":"custom",
               "tokenizer":"standard",
               "filter":[
                  "lowercase",
                  "german_dict_decompounder",
                  "german_normalization",
                  "german_stemmer"
               ]
            },
            "german_decompound":{
               "type":"custom",
               "tokenizer":"standard",
               "filter":[
                  "lowercase",
                  "german_decompounder",
                  "german_normalization",
                  "german_stemmer"
               ]
            },
            "german_stop": {
               "tokenizer": "standard",
               "filter": [
                   "lowercase",
                   "german_decompounder",
                   "german_stop",
                   "german_normalization",
                   "german_stemmer"
               ]
            }
         }
      }
   },
   "mappings":{
         "properties":{
            "product_name":{
               "type":"text",
               "copy_to":"search",
               "analyzer":"standard"
            },
            "short_description":{
               "type":"text",
               "copy_to":"search",
               "analyzer":"german_decompound"
            },
            "long_description":{
               "type":"text",
               "copy_to":"search",
               "analyzer":"german_stop"
            },
            "search":{
               "type":"text",
               "analyzer":"german_decompound"
            }
         }
      }
}
'
