version: '3.9'

services:

  es:
    build:
      dockerfile: Dockerfile-elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601

  logstash:
    image: logstash:7.17.0
    container_name: logstash
    restart: always
