FROM elasticsearch:7.17.0

LABEL maintainer="mhteaching2703@gmail.com"

# Copy src to /src
COPY src /src
# Install scripts
RUN     /src/install-apt.sh \
    && /src/basic_tools.sh \
    && cd /usr/share/elasticsearch/config \
    && mkdir analysis \
    && chown elasticsearch:root analysis \
    && cd analysis \
    && git clone https://github.com/uschindler/german-decompounder.git . \
    && chown elasticsearch:root *
